title: The Wilke Lab
address: The University of Texas at Austin
email: wilke@austin.utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  Department of Integrative Biology<br>
  Institute for Cellular and Molecular Biology<br>
  2500 Speedway, A4800<br>
  Room: MBB 3.232
baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ClausWilke
github_username:  wilkelab
instagram_username: wilkelab

# Build settings
markdown: kramdown
